<?php

use Illuminate\Database\Seeder;


class LangTableSeeder extends Seeder
{


    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $langs = $this->langs();
        DB::table('langs')->insert($langs);

        $langfiles = $this->langFiles();
        DB::table('lang_files')->insert($langfiles);

        $lang=\App\Models\Lang::where('iso', 'en')->first();
        $langController = new \App\Http\Controllers\Backend\LangController();
        $langController->loadFiles($lang, 'resources/lang/');

        DB::table('langs')->where('iso', 'en')->update(['available' => true]);
    }

    private function langFiles()
    {
        $now = \Carbon\Carbon::now()->format('Y-m-d H:i:s');
        $filePaths = $this->getLangFiles();

        foreach ($filePaths as $fs) {
            $file = pathinfo($fs);
            $filename = $file['filename'];
            $filedir= $file['dirname'];
            $path = str_replace('resources/lang/en/', "", $filedir."/");
            $path = str_replace('resources/lang/en', "", $path);
            $lang_files_array[] = ["name" => $filename, "path" => $path, "parent_id" => 0, "created_at" => $now, "updated_at" => $now];
        }

        return $lang_files_array;

    }

    private function getLangFiles($path='resources/lang/en')
    {


        $dirs = array_filter(glob($path . '/*'), 'is_dir');

        $result = glob($path . '/*.php');

        foreach ($dirs as $dir) {

            if (count(array_filter(glob($dir . '/*'), 'is_dir')) > 0) {

                $result = array_merge($result, $this->getLangFiles($dir));


            } else {
                $result = array_merge($result, glob($dir . '/*.php'));
            }
        }

        return $result;
    }

    private function langs()
    {

        $now = \Carbon\Carbon::now()->format('Y-m-d H:i:s');
        return [
            ["iso" => "af-ZA", "name" => "Afrikaans (South Africa)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "af", "name" => "Afrikaans", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ak-GH", "name" => "Akan (Ghana)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ak", "name" => "Akan", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sq-AL", "name" => "Albanian (Albania)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sq", "name" => "Albanian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "am-ET", "name" => "Amharic (Ethiopia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "am", "name" => "Amharic", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "af-NA", "name" => "Afrikaans (Namibia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-DZ", "name" => "Arabic (Algeria)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-BH", "name" => "Arabic (Bahrain)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-EG", "name" => "Arabic (Egypt)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-IQ", "name" => "Arabic (Iraq)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-JO", "name" => "Arabic (Jordan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-KW", "name" => "Arabic (Kuwait)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-LB", "name" => "Arabic (Lebanon)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-LY", "name" => "Arabic (Libya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-MA", "name" => "Arabic (Morocco)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-OM", "name" => "Arabic (Oman)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-QA", "name" => "Arabic (Qatar)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-SA", "name" => "Arabic (Saudi Arabia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-SD", "name" => "Arabic (Sudan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-SY", "name" => "Arabic (Syria)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-TN", "name" => "Arabic (Tunisia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-AE", "name" => "Arabic (United Arab Emirates)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar-YE", "name" => "Arabic (Yemen)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ar", "name" => "Arabic", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "hy-AM", "name" => "Armenian (Armenia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "hy", "name" => "Armenian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "as-IN", "name" => "Assamese (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "as", "name" => "Assamese", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "asa-TZ", "name" => "Asu (Tanzania)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "asa", "name" => "Asu", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "az-Cyrl", "name" => "Azerbaijani (Cyrillic)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "az-Cyrl-AZ", "name" => "Azerbaijani (Cyrillic), Azerbaijan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "az-Latn", "name" => "Azerbaijani (Latin)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "az-Latn-AZ", "name" => "Azerbaijani (Latin), Azerbaijan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "az", "name" => "Azerbaijani", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bm-ML", "name" => "Bambara (Mali)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bm", "name" => "Bambara", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "eu-ES", "name" => "Basque (Spain)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "eu", "name" => "Basque", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "be-BY", "name" => "Belarusian (Belarus)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "be", "name" => "Belarusian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bem-ZM", "name" => "Bemba (Zambia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bem", "name" => "Bemba", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bez-TZ", "name" => "Bena (Tanzania)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bez", "name" => "Bena", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bn-BD", "name" => "Bengali (Bangladesh)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bn-IN", "name" => "Bengali (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bn", "name" => "Bengali", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bs-BA", "name" => "Bosnian (Bosnia and Herzegovina)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bs", "name" => "Bosnian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bg-BG", "name" => "Bulgarian (Bulgaria)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bg", "name" => "Bulgarian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "my-MM", "name" => "Burmese (Myanmar (Burma))", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "my", "name" => "Burmese", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ca-ES", "name" => "Catalan (Spain)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ca", "name" => "Catalan", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "tzm-Latn", "name" => "Central Morocco Tamazight (Latin)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "tzm-Latn-MA", "name" => "Central Morocco Tamazight (Latin), Morocco)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "tzm", "name" => "Central Morocco Tamazight", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "chr-US", "name" => "Cherokee (United States)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "chr", "name" => "Cherokee", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "cgg-UG", "name" => "Chiga (Uganda)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "cgg", "name" => "Chiga", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "zh-Hans", "name" => "Chinese (Simplified Han)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "zh-Hans-CN", "name" => "Chinese (Simplified Han), China)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "zh-Hans-HK", "name" => "Chinese (Simplified Han), Hong Kong SAR China)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "zh-Hans-MO", "name" => "Chinese (Simplified Han), Macau SAR China)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "zh-Hans-SG", "name" => "Chinese (Simplified Han), Singapore)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "zh-Hant", "name" => "Chinese (Traditional Han)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "zh-Hant-HK", "name" => "Chinese (Traditional Han), Hong Kong SAR China)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "zh-Hant-MO", "name" => "Chinese (Traditional Han), Macau SAR China)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "zh-Hant-TW", "name" => "Chinese (Traditional Han), Taiwan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "zh", "name" => "Chinese", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kw-GB", "name" => "Cornish (United Kingdom)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kw", "name" => "Cornish", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "hr-HR", "name" => "Croatian (Croatia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "hr", "name" => "Croatian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "cs-CZ", "name" => "Czech (Czech Republic)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "cs", "name" => "Czech", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "da-DK", "name" => "Danish (Denmark)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "da", "name" => "Danish", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "nl-BE", "name" => "Dutch (Belgium)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "nl-NL", "name" => "Dutch (Netherlands)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "nl", "name" => "Dutch", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ebu-KE", "name" => "Embu (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ebu", "name" => "Embu", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-AS", "name" => "English (American Samoa)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-AU", "name" => "English (Australia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-BE", "name" => "English (Belgium)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-BZ", "name" => "English (Belize)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-BW", "name" => "English (Botswana)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-CA", "name" => "English (Canada)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-GU", "name" => "English (Guam)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-HK", "name" => "English (Hong Kong SAR China)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-IN", "name" => "English (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-IE", "name" => "English (Ireland)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-JM", "name" => "English (Jamaica)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-MT", "name" => "English (Malta)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-MH", "name" => "English (Marshall Islands)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-MU", "name" => "English (Mauritius)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-NA", "name" => "English (Namibia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-NZ", "name" => "English (New Zealand)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-MP", "name" => "English (Northern Mariana Islands)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-PK", "name" => "English (Pakistan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-PH", "name" => "English (Philippines)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-SG", "name" => "English (Singapore)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-ZA", "name" => "English (South Africa)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-TT", "name" => "English (Trinidad and Tobago)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-UM", "name" => "English (U.S. Minor Outlying Islands)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-VI", "name" => "English (U.S. Virgin Islands)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-GB", "name" => "English (United Kingdom)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-US", "name" => "English (United States)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en-ZW", "name" => "English (Zimbabwe)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "en", "name" => "English", "active" => 1, "available" => 1, "default" => 1, "created_at" => $now, "updated_at" => $now],
            ["iso" => "eo", "name" => "Esperanto", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "et-EE", "name" => "Estonian (Estonia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "et", "name" => "Estonian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ee-GH", "name" => "Ewe (Ghana)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ee-TG", "name" => "Ewe (Togo)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ee", "name" => "Ewe", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fo-FO", "name" => "Faroese (Faroe Islands)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fo", "name" => "Faroese", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fil-PH", "name" => "Filipino (Philippines)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fil", "name" => "Filipino", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fi-FI", "name" => "Finnish (Finland)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fi", "name" => "Finnish", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-BE", "name" => "French (Belgium)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-BJ", "name" => "French (Benin)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-BF", "name" => "French (Burkina Faso)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-BI", "name" => "French (Burundi)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-CM", "name" => "French (Cameroon)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-CA", "name" => "French (Canada)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-CF", "name" => "French (Central African Republic)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-TD", "name" => "French (Chad)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-KM", "name" => "French (Comoros)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-CG", "name" => "French (Congo - Brazzaville)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-CD", "name" => "French (Congo - Kinshasa)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-CI", "name" => "French (Côte d'Ivoire)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-DJ", "name" => "French (Djibouti)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-GQ", "name" => "French (Equatorial Guinea)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-FR", "name" => "French (France)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-GA", "name" => "French (Gabon)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-GP", "name" => "French (Guadeloupe)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-GN", "name" => "French (Guinea)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-LU", "name" => "French (Luxembourg)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-MG", "name" => "French (Madagascar)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-ML", "name" => "French (Mali)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-MQ", "name" => "French (Martinique)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-MC", "name" => "French (Monaco)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-NE", "name" => "French (Niger)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-RW", "name" => "French (Rwanda)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-RE", "name" => "French (Réunion)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-BL", "name" => "French (Saint Barthémy)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-MF", "name" => "French (Saint Martin)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-SN", "name" => "French (Senegal)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-CH", "name" => "French (Switzerland)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr-TG", "name" => "French (Togo)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fr", "name" => "French", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ff-SN", "name" => "Fulah (Senegal)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ff", "name" => "Fulah", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "gl-ES", "name" => "Galician (Spain)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "gl", "name" => "Galician", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "lg-UG", "name" => "Ganda (Uganda)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "lg", "name" => "Ganda", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ka-GE", "name" => "Georgian (Georgia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ka", "name" => "Georgian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "de-AT", "name" => "German (Austria)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "de-BE", "name" => "German (Belgium)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "de-DE", "name" => "German (Germany)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "de-LI", "name" => "German (Liechtenstein)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "de-LU", "name" => "German (Luxembourg)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "de-CH", "name" => "German (Switzerland)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "de", "name" => "German", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "el-CY", "name" => "Greek (Cyprus)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "el-GR", "name" => "Greek (Greece)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "el", "name" => "Greek", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "gu-IN", "name" => "Gujarati (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "gu", "name" => "Gujarati", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "guz-KE", "name" => "Gusii (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "guz", "name" => "Gusii", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ha-Latn", "name" => "Hausa (Latin)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ha-Latn-GH", "name" => "Hausa (Latin), Ghana)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ha-Latn-NE", "name" => "Hausa (Latin), Niger)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ha-Latn-NG", "name" => "Hausa (Latin), Nigeria)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ha", "name" => "Hausa", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "haw-US", "name" => "Hawaiian (United States)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "haw", "name" => "Hawaiian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "he-IL", "name" => "Hebrew (Israel)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "he", "name" => "Hebrew", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "hi-IN", "name" => "Hindi (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "hi", "name" => "Hindi", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "hu-HU", "name" => "Hungarian (Hungary)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "hu", "name" => "Hungarian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "is-IS", "name" => "Icelandic (Iceland)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "is", "name" => "Icelandic", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ig-NG", "name" => "Igbo (Nigeria)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ig", "name" => "Igbo", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "id-ID", "name" => "Indonesian (Indonesia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "id", "name" => "Indonesian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ga-IE", "name" => "Irish (Ireland)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ga", "name" => "Irish", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "it-IT", "name" => "Italian (Italy)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "it-CH", "name" => "Italian (Switzerland)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "it", "name" => "Italian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ja-JP", "name" => "Japanese (Japan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ja", "name" => "Japanese", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kea-CV", "name" => "Kabuverdianu (Cape Verde)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kea", "name" => "Kabuverdianu", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kab-DZ", "name" => "Kabyle (Algeria)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kab", "name" => "Kabyle", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kl-GL", "name" => "Kalaallisut (Greenland)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kl", "name" => "Kalaallisut", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kln-KE", "name" => "Kalenjin (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kln", "name" => "Kalenjin", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kam-KE", "name" => "Kamba (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kam", "name" => "Kamba", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kn-IN", "name" => "Kannada (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kn", "name" => "Kannada", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kk-Cyrl", "name" => "Kazakh (Cyrillic)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kk-Cyrl-KZ", "name" => "Kazakh ((Cyrillic), Kazakhstan))", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kk", "name" => "Kazakh", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "km-KH", "name" => "Khmer (Cambodia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "km", "name" => "Khmer", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ki-KE", "name" => "Kikuyu (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ki", "name" => "Kikuyu", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "rw-RW", "name" => "Kinyarwanda (Rwanda)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "rw", "name" => "Kinyarwanda", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kok-IN", "name" => "Konkani (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kok", "name" => "Konkani", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ko-KR", "name" => "Korean (South Korea)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ko", "name" => "Korean", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "khq-ML", "name" => "Koyra Chiini (Mali)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "khq", "name" => "Koyra Chiini", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ses-ML", "name" => "Koyraboro Senni (Mali)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ses", "name" => "Koyraboro Senni", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "lag-TZ", "name" => "Langi (Tanzania)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "lag", "name" => "Langi", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "lv-LV", "name" => "Latvian (Latvia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "lv", "name" => "Latvian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "lt-LT", "name" => "Lithuanian (Lithuania)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "lt", "name" => "Lithuanian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "luo-KE", "name" => "Luo (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "luo", "name" => "Luo", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "luy-KE", "name" => "Luyia (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "luy", "name" => "Luyia", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mk-MK", "name" => "Macedonian (Macedonia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mk", "name" => "Macedonian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "jmc-TZ", "name" => "Machame (Tanzania)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "jmc", "name" => "Machame", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kde-TZ", "name" => "Makonde (Tanzania)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "kde", "name" => "Makonde", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mg-MG", "name" => "Malagasy (Madagascar)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mg", "name" => "Malagasy", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ms-BN", "name" => "Malay (Brunei)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ms-MY", "name" => "Malay (Malaysia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ms", "name" => "Malay", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ml-IN", "name" => "Malayalam (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ml", "name" => "Malayalam", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mt-MT", "name" => "Maltese (Malta)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mt", "name" => "Maltese", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "gv-GB", "name" => "Manx (United Kingdom)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "gv", "name" => "Manx", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mr-IN", "name" => "Marathi (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mr", "name" => "Marathi", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mas-KE", "name" => "Masai (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mas-TZ", "name" => "Masai (Tanzania)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mas", "name" => "Masai", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mer-KE", "name" => "Meru (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mer", "name" => "Meru", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mfe-MU", "name" => "Morisyen (Mauritius)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "mfe", "name" => "Morisyen", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "naq-NA", "name" => "Nama (Namibia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "naq", "name" => "Nama", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ne-IN", "name" => "Nepali (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ne-NP", "name" => "Nepali (Nepal)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ne", "name" => "Nepali", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "nd-ZW", "name" => "North Ndebele (Zimbabwe)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "nd", "name" => "North Ndebele", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "nb-NO", "name" => "Norwegian Bokmal (Norway)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "nb", "name" => "Norwegian Bokmal", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "nn-NO", "name" => "Norwegian Nynorsk (Norway)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "nn", "name" => "Norwegian Nynorsk", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "nyn-UG", "name" => "Nyankole (Uganda)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "nyn", "name" => "Nyankole", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "or-IN", "name" => "Oriya (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "or", "name" => "Oriya", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "om-ET", "name" => "Oromo (Ethiopia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "om-KE", "name" => "Oromo (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "om", "name" => "Oromo", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ps-AF", "name" => "Pashto (Afghanistan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ps", "name" => "Pashto", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fa-AF", "name" => "Persian (Afghanistan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fa-IR", "name" => "Persian (Iran)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "fa", "name" => "Persian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "pl-PL", "name" => "Polish (Poland)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "pl", "name" => "Polish", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "pt-BR", "name" => "Portuguese (Brazil)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "pt-GW", "name" => "Portuguese (Guinea-Bissau)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "pt-MZ", "name" => "Portuguese (Mozambique)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "pt-PT", "name" => "Portuguese (Portugal)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "pt", "name" => "Portuguese", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "pa-Arab", "name" => "Punjabi (Arabic)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "pa-Arab-PK", "name" => "Punjabi (Arabic), Pakistan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "pa-Guru", "name" => "Punjabi (Gurmukhi)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "pa-Guru-IN", "name" => "Punjabi (Gurmukhi), India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "pa", "name" => "Punjabi", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ro-MD", "name" => "Romanian (Moldova)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ro-RO", "name" => "Romanian (Romania)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ro", "name" => "Romanian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "rm-CH", "name" => "Romansh (Switzerland)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "rm", "name" => "Romansh", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "rof-TZ", "name" => "Rombo (Tanzania)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "rof", "name" => "Rombo", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ru-MD", "name" => "Russian (Moldova)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ru-RU", "name" => "Russian (Russia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ru-UA", "name" => "Russian (Ukraine)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ru", "name" => "Russian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "rwk-TZ", "name" => "Rwa (Tanzania)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "rwk", "name" => "Rwa", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "saq-KE", "name" => "Samburu (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "saq", "name" => "Samburu", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sg-CF", "name" => "Sango (Central African Republic)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sg", "name" => "Sango", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "seh-MZ", "name" => "Sena (Mozambique)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "seh", "name" => "Sena", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sr-Cyrl", "name" => "Serbian (Cyrillic)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sr-Cyrl-BA", "name" => "Serbian (Cyrillic), Bosnia and Herzegovina)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sr-Cyrl-ME", "name" => "Serbian (Cyrillic), Montenegro)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sr-Cyrl-RS", "name" => "Serbian (Cyrillic), Serbia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sr-Latn", "name" => "Serbian (Latin)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sr-Latn-BA", "name" => "Serbian (Latin), Bosnia and Herzegovina)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sr-Latn-ME", "name" => "Serbian (Latin), Montenegro)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sr-Latn-RS", "name" => "Serbian (Latin), Serbia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sr", "name" => "Serbian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sn-ZW", "name" => "Shona (Zimbabwe)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sn", "name" => "Shona", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ii-CN", "name" => "Sichuan Yi (China)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ii", "name" => "Sichuan Yi", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "si-LK", "name" => "Sinhala (Sri Lanka)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "si", "name" => "Sinhala", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sk-SK", "name" => "Slovak (Slovakia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sk", "name" => "Slovak", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sl-SI", "name" => "Slovenian (Slovenia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sl", "name" => "Slovenian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "xog-UG", "name" => "Soga (Uganda)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "xog", "name" => "Soga", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "so-DJ", "name" => "Somali (Djibouti)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "so-ET", "name" => "Somali (Ethiopia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "so-KE", "name" => "Somali (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "so-SO", "name" => "Somali (Somalia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "so", "name" => "Somali", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-AR", "name" => "Spanish (Argentina)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-BO", "name" => "Spanish (Bolivia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-CL", "name" => "Spanish (Chile)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-CO", "name" => "Spanish (Colombia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-CR", "name" => "Spanish (Costa Rica)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-DO", "name" => "Spanish (Dominican Republic)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-EC", "name" => "Spanish (Ecuador)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-SV", "name" => "Spanish (El Salvador)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-GQ", "name" => "Spanish (Equatorial Guinea)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-GT", "name" => "Spanish (Guatemala)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-HN", "name" => "Spanish (Honduras)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-419", "name" => "Spanish (Latin America)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-MX", "name" => "Spanish (Mexico)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-NI", "name" => "Spanish (Nicaragua)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-PA", "name" => "Spanish (Panama)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-PY", "name" => "Spanish (Paraguay)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-PE", "name" => "Spanish (Peru)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-PR", "name" => "Spanish (Puerto Rico)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-ES", "name" => "Spanish (Spain)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-US", "name" => "Spanish (United States)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-UY", "name" => "Spanish (Uruguay)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es-VE", "name" => "Spanish (Venezuela)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "es", "name" => "Spanish", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sw-KE", "name" => "Swahili (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sw-TZ", "name" => "Swahili (Tanzania)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sw", "name" => "Swahili", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sv-FI", "name" => "Swedish (Finland)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sv-SE", "name" => "Swedish (Sweden)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "sv", "name" => "Swedish", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "gsw-CH", "name" => "Swiss German (Switzerland)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "gsw", "name" => "Swiss German", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "shi-Latn", "name" => "Tachelhit (Latin)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "shi-Latn-MA", "name" => "Tachelhit (Latin), Morocco)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "shi-Tfng", "name" => "Tachelhit (Tifinagh)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "shi-Tfng-MA", "name" => "Tachelhit (Tifinagh), Morocco)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "shi", "name" => "Tachelhit", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "dav-KE", "name" => "Taita (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "dav", "name" => "Taita", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ta-IN", "name" => "Tamil (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ta-LK", "name" => "Tamil (Sri Lanka)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ta", "name" => "Tamil", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "te-IN", "name" => "Telugu (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "te", "name" => "Telugu", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "teo-KE", "name" => "Teso (Kenya)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "teo-UG", "name" => "Teso (Uganda)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "teo", "name" => "Teso", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "th-TH", "name" => "Thai (Thailand)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "th", "name" => "Thai", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bo-CN", "name" => "Tibetan (China)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bo-IN", "name" => "Tibetan (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "bo", "name" => "Tibetan", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ti-ER", "name" => "Tigrinya (Eritrea)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ti-ET", "name" => "Tigrinya (Ethiopia)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ti", "name" => "Tigrinya", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "to-TO", "name" => "Tonga (Tonga)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "to", "name" => "Tonga", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "tr-TR", "name" => "Turkish (Turkey)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "tr", "name" => "Turkish", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "uk-UA", "name" => "Ukrainian (Ukraine)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "uk", "name" => "Ukrainian", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ur-IN", "name" => "Urdu (India)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ur-PK", "name" => "Urdu (Pakistan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "ur", "name" => "Urdu", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "uz-Arab", "name" => "Uzbek (Arabic)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "uz-Arab-AF", "name" => "Uzbek (Arabic), Afghanistan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "uz-Cyrl", "name" => "Uzbek (Cyrillic)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "uz-Cyrl-UZ", "name" => "Uzbek (Cyrillic), Uzbekistan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "uz-Latn", "name" => "Uzbek (Latin)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "uz-Latn-UZ", "name" => "Uzbek (Latin), Uzbekistan)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "uz", "name" => "Uzbek", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "vi-VN", "name" => "Vietnamese (Vietnam)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "vi", "name" => "Vietnamese", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "vun-TZ", "name" => "Vunjo (Tanzania)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "vun", "name" => "Vunjo", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "cy-GB", "name" => "Welsh (United Kingdom)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "cy", "name" => "Welsh", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "yo-NG", "name" => "Yoruba (Nigeria)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "yo", "name" => "Yoruba", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "zu-ZA", "name" => "Zulu (South Africa)", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now],
            ["iso" => "zu", "name" => "Zulu", "active" => 0, "available" => 0, "default" => 0, "created_at" => $now, "updated_at" => $now]
        ];


    }

}